- hosts: docker

  tasks:

  - name: "Creating  An yum repo for docker..... "
    yum_repository:
            name: "docker"
            description: "repo for DOcker"
            baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
            gpgcheck: no

  - name: "Installing Docker ....."
    package:
       name: "docker-ce-18.09.1-3.el7.x86_64"
       state: present

  - name: "Satarting Docker Service ....."
    service:
            name: "docker"
            state: started

  - name: "docker_image module need an python module i.e. docker-py ..."
    pip:
      name: docker-py